import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navigation/Navbar";

export const metadata: Metadata = {
  title: "I'm Rizky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
